### ISSUE TITLE
Instance context methods are not supported

### ISSUE THREAD

**Issue by Abrakadabr** [zzzprojects/Z.Expressions.Eval#1]
EvalContext documentation:

> Problem: You need to evaluate a dynamic C# code in an instance context.

My example:

```
public class Custom
{
    public int Add(int a, int b)
    {
        return a + b;
    }
}

new EvalContext().Execute<int>("Add(1, 2)", new Custom()); // exception: No applicable member has been found for the expression.
```

**Comment by zzzprojects** [comment]
Thank you for reporting.

You are right, if only one entity is passed, instance method should be available without having to prefix.

By example, following code work:

``` csharp
var i = new EvalContext().Execute<int>("{0}.Add(1, 2)", new Custom());
```

But we should not force you to prefix with "{0}.".

We will review this request and try to make add support to instance method this week-end.

**Comment by zzzprojects** [comment]
Sorry for the delay,

We just release the v1.0.18 which now support method without having to prefix when only one parameter is used.

Let us know if it's now working for you.

Best Regards,

Jonathan

**Comment by Abrakadabr** [comment]
Thanks, it works.

**Comment by zzzprojects** [comment]
Closing: User confirmed it works.
