### ISSUE TITLE
Strange memory of previous values...

### ISSUE THREAD

**Issue by jsobell** [zzzprojects/Z.Expressions.Eval#10]
If I evaluate the expression:
`new { a=1, b="B"};`
I would expect to subsequently evaluate the expression
`new { a="1", b="B"};`
But doing this raises the error:
`Argument type 'System.String' does not match the corresponding member type 'System.Int32'`
because it's somehow remembering the nested anonymous object type's *a* variable is an integer.
Is this a bug, or is there a way to prevent this context caching or 'remembering' these data types?

**Comment by JonathanMagnan** [comment]
Hello @jsobell ,

Thank you for reporting, we will look at this issue very soon.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @jsobell ,

The v2.1.11 has been released ([Release Note](https://github.com/zzzprojects/Eval-Expression.NET/releases/tag/v2.1.11))
https://www.nuget.org/packages/Z.Expressions.Eval/

The constructors for anonymous type are now generic as well.

Let me know if that fixed your issue.

Best Regards,

Jonathan

**Comment by jsobell** [comment]
Yep, that seems to be working nicely!

Many thanks for the speed fix!

Cheers,
 Jason
