### ISSUE TITLE
RegEx Support

### ISSUE THREAD

**Issue by stonstad** [zzzprojects/Z.Expressions.Eval#101]
Is there support for RegEx?  If so, how does one go about using/integrating it?

**Comment by JonathanMagnan** [comment]
Hello @stonstad ,

What do you mean by `RegEx` support? It should always be supported.

Example:

```csharp
string input = "Hello   World   ";
string pattern = "\\s+";
string replacement = " ";

var result = Eval.Execute(@"Regex rgx = new Regex(pattern); return rgx.Replace(input, replacement);", new {pattern, input, replacement});
```

Let me know if you still have an issue to use it or if everything is fine.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @stonstad ,

Since our last conversation, we haven't heard from you!

Did you get the chance to look at the example?

Don't hesitate to contact us with any questions or further assistance, 

Jon

**Comment by stonstad** [comment]
Yes, it works great.  Thank you!
