### ISSUE TITLE
Seems doesn't support EF.Functions??

### ISSUE THREAD

**Issue by noezad** [zzzprojects/Z.Expressions.Eval#102]
The following statement will report an error.

 var allEvent = await (from n in _context.Events
                                  .WhereDynamic(c => "EF.Functions.Contains(c.UseInSearch, search) && c.IsDelete == false") ...

The error is as follows

EvalException: Oops! No applicable member has been found for the expression.
Tnx

**Comment by JonathanMagnan** [comment]
Hello @noezad ,

Could you provide your EF version including the EF provider package you are using,

My developer did a test and it's worked on his side, so perhaps that's a package we didn't include yet.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @noezad ,

Since our last conversation, we haven't heard from you!

Don't hesitate to provide your EF version and the EF provider package you are using, so we can assist you better!

Looking forward to hearing from you, 

Jon

**Comment by noezad** [comment]
Hi Jon,tnx for your massage
I am using Ef 3.1 and Sql Server 
Have a good time

**Comment by JonathanMagnan** [comment]
Hello @noezad ,

This version seems to work.

What exactly is the `search` in your expression? It doesn't look to be provided in the parameter. So perhaps the issue is something else and that would explain why that's working for us.

**Comment by JonathanMagnan** [comment]
If you still have the problem, it is possible for you to provide a runnable project with the minimum code to reproduce the problem?

It will greatly help us to fix it instead of trying to reproduce it.

Best Regards,

Jon

**Comment by noezad** [comment]
Hello Sir ,
Yes, this problem is not solved yet, I will try to share with you a small project that has this problem in the next 2 days.

Tnx

Noezad

**Comment by noezad** [comment]
Hello @JonathanMagnan ,

I found the cause of the problem

This code works correctly:

var allEvent = await (from n in _context.Events
                      .WhereDynamic(c => "EF.Functions.FreeText(c.UseInSearch,\"test*\" ) && c.IsDelete == false")...

But This code does not work correctly:

string searchText='"' + "test" + '*' + '"';
var allEvent = await (from n in _context.Events
                      .WhereDynamic(c => "EF.Functions.FreeText(c.UseInSearch, searchText) && c.IsDelete == false")...

I tried different methods to correct this string(searchText), but each time my attempt failed.

Tnx

**Comment by noezad** [comment]
Done!

string searchText='"' + "test" + '*' + '"';
string query="c =>EF.Functions.FreeText(c.UseInSearch," + searchText + ") && c.IsDelete == false";
var allEvent = await (from n in _context.Events
.WhereDynamic(query)...

Best Regards,

Noezad

**Comment by JonathanMagnan** [comment]
Awesome,

If I understand correctly, everything is now working?

It's also possible to pass parameter with an anonymous type:

```csharp
var list = ctx.WhereDynamic(x => "x > y", new { y = 2 }).ToList();
```
