### ISSUE TITLE
Is Compilation Automatic?

### ISSUE THREAD

**Issue by stonstad** [zzzprojects/Z.Expressions.Eval#104]
When is compilation performed for an expression?  Is it automatically performed if caching is enabled, or must I manually compile expressions?

**Comment by JonathanMagnan** [comment]
Hello @stonstad ,

I'm not sure to 100% understand your question but I will try to answer it.

When you execute an expression,

- Our library firstly try to check if the compiled lambda is already cached. If yes, it returns and uses it
- If not cached, the `execute` will automatically call the `compile` then cache it
- Then will use the returned compiled lambda for the `execute`

So no, you do not have to manually call the compile. Our library is smart enough to do it. On a very big loop, the compiled method will always be faster than the execute method. However, using the `Execute` method is usually enough as checking if the compiled lambda exists or not is really fast.

Let me know if that answers your question.

Best Regards,

Jon

**Comment by stonstad** [comment]
Answered perfectly.  Thank you Jon!
