### ISSUE TITLE
Exception handling nulls

### ISSUE THREAD

**Issue by TheoVC** [zzzprojects/Z.Expressions.Eval#105]
This produces an exception, when it should return false

`Eval.Execute(" null != null " )`

**Comment by JonathanMagnan** [comment]
Hello @TheoVC ,

Thank you for reporting, my developer will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @TheoVC ,

The v4.0.45 has been released.

Could you try it and let us know if everything is now working with nullable value?

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @TheoVC ,

Since our last conversation, we haven't heard from you!

Did you get the chance to test the fix in the new version?

Don't hesitate to contact once you do!

Best regards,

Jon
