### ISSUE TITLE
Something wrong with typeof

### ISSUE THREAD

**Issue by cesaryuan** [zzzprojects/Z.Expressions.Eval#106]
This will throw an error, but it should not.
```csharp
 new EvalContext().Execute("typeof(string).Assembly");
```
Error
```
Oops! A null expression has been found. A not null statement was expected.. The error occurred for expression "." at position 14 near ".Assembly".
```

**Comment by JonathanMagnan** [comment]
Thank you for reporting @cesaryuan ,

We can successfully reproduce the error. There is a special logic we apply for type, we will try to remember why we did this logic which causes this error when trying to get a property for the type.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @cesaryuan ,

The v4.0.47 has been released.

Could you try it and let us know if everything is working?

Best Regards,

Jon

**Comment by cesaryuan** [comment]
> Hello @cesaryuan ,
> 
> The v4.0.47 has been released.
> 
> Could you try it and let us know if everything is working?
> 
> Best Regards,
> 
> Jon

I works, thank u!

**Comment by cesaryuan** [comment]
It seems that the problem still exists. I try the following expression, and it throws error.
```
typeof(string).GetMethods();
```

**Comment by JonathanMagnan** [comment]
Thank you for reporting @cesaryuan ,

My developer will look at it. Probably the same issue as the original one but this time on methods.

**Comment by JonathanMagnan** [comment]
Hello @cesaryuan ,

The v4.0.51 has been released.

Could you test it and let us know if we fixed it successfully?

**Comment by cesaryuan** [comment]
Thank you so much! It has worked!
