### ISSUE TITLE
Handling exceptions for ZExpression

### ISSUE THREAD

**Issue by thomshib** [zzzprojects/Z.Expressions.Eval#107]
I have a Z expression Z.Expression.EvalContext.Compile<Func<TInput,TResult>>(string..) call. This compiled expression is invalid state <Internal error Evaluating expression>. 

How do I check for this error state so that I can handle it and throw a user defined exception?

**Comment by JonathanMagnan** [comment]
Hello @thomshib ,

We currently have an `EvalException` which can give you some information but it still doesn't support all cases. You still have to catch the general exception as well.

```csharp
try
{
	var compile = Eval.Compile("1 * #2018-01-01#");
}
catch(EvalException evalException)
{
	var token = evalException.Token;
	var message = evalException.Message;
}
catch(Exception exception)
{
	var message = exception.Message;
}
```

Let me know if that answers your question.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @thomshib ,

Since our last conversation, I haven't heard from you!

Let me know if you need more information or assistance about how to handle the exception.

Looking forward to hearing from you, 

Jon

**Comment by JonathanMagnan** [comment]
Hello again @thomshib !

A simple reminder that we are here to assist you!

Don't hesitate to contact us if you need further assistance about how to handle the exception.

Best regards,

Jon
