### ISSUE TITLE
An error occurred while parsing the interpolated string.

### ISSUE THREAD

**Issue by cesaryuan** [zzzprojects/Z.Expressions.Eval#108]
The following code throws an exception, but it should work. Is there any problem when analyzing the `interpolated string`?
```csharp
new EvalContext().Execute("$\"{\"1\"}\"");  // just $"{"1"}"
```
Exception message
```
Object reference not set to an instance of an object.
```

**Comment by JonathanMagnan** [comment]
Hello @cesaryuan ,

Thank you for reporting,

It looks indeed like a case that we never tested.

My developer will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @cesaryuan ,

The v4.0.48 has been released.

Several issues similar to this one has been fixed in this release.

Could you try it and let us know if everything works fine with your expression?

Best Regards,

Jon

**Comment by cesaryuan** [comment]
> Hello @cesaryuan ,
> 
> The v4.0.48 has been released.
> 
> Several issues similar to this one has been fixed in this release.
> 
> Could you try it and let us know if everything works fine with your expression?
> 
> Best Regards,
> 
> Jon

It Works great, thx.
