### ISSUE TITLE
EvalContext.Compile behaviour change 4.0.43 to 4.0.47

### ISSUE THREAD

**Issue by Cynicszm** [zzzprojects/Z.Expressions.Eval#109]
Hi,

Has the behaviour of EvalContext.Compile changed between 4.0.43 and 4.0.47?

The statement below works as expected in 4.0.43 but fails with **Oops! No applicable member has been found for the expression** in 4.0.47

` var compiledExpression = evalContext.Compile<Func<TemplateRowReader, object>>(expression);`

**Comment by JonathanMagnan** [comment]
Hello @Cynicszm ,

Is it possible to know the current `expression` you are using? Or a runnable example

That will help us to better understand what happened here.

Best Regards,

Jon

**Comment by Cynicszm** [comment]
Many thanks for the quick response Jon, my apologies turns out it was a dumb user error. 

John

**Comment by JonathanMagnan** [comment]
Glad to hear that it was sorted out!

Don't hesitate to contact us with any questions, issues, or feedback!

Best regards,

Jon
