### ISSUE TITLE
No applicable member?

### ISSUE THREAD

**Issue by cesaryuan** [zzzprojects/Z.Expressions.Eval#113]
Execute the following statement by EvalContext throws an error, could you please check it out?
```
(new List<string>() as IEnumerable<string>).FirstOrDefault()
```
Error Message throwed
```
Oops! No applicable member has been found for the expression. The error occurred for expression "." at position 43 near ".FirstOrDefault()".
```
Incorrect number of arguments supplied for lambda invocation

**Comment by JonathanMagnan** [comment]
Hello @cesaryuan ,

Thank you for reporting, we will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @cesaryuan ,

The v4.0.51 has been released.

Could you test it and let us know if we fixed it successfully?

**Comment by cesaryuan** [comment]
Thank you so much! It has worked!
