### ISSUE TITLE
Compile fail

### ISSUE THREAD

**Issue by samchenws** [zzzprojects/Z.Expressions.Eval#114]
Eval.Compile<Func<string, string>>(code, param)
When param="" ,throw Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'startIndex')

**Comment by JonathanMagnan** [comment]
Hello @samchenws ,

Thank you for reporting.

The v4.0.52 has been released

The error message has been improved indicating that a variable name cannot be empty.

Best Regards,

Jon
