### ISSUE TITLE
Strange return value with "_context"

### ISSUE THREAD

**Issue by cuiliang** [zzzprojects/Z.Expressions.Eval#115]
https://dotnetfiddle.net/6IEtGc

code:
```c#
// @nuget: Z.Expressions.Eval

using System;
using Z.Expressions;
using System.Collections.Generic;
					
public class Program
{
	public static void Main()
	{
		// From simple expression...
		
		var dict = new Dictionary<string, object>();
		dict.Add("_context", "aaa");
		// To complex code.
		var result = Eval.Execute("\"_context\"", dict);
		
		Console.WriteLine(result);		
		
	}
}
```

returns `zzz_f900d830_3564_44fc_a449_570a57c64ff5` which should return a string `_context` .

![image](https://user-images.githubusercontent.com/1972649/135054368-f14eaf47-20ef-43e3-baa2-ffb80f99eaf1.png)

**Comment by cuiliang** [comment]
remove `_` from variable name will return correct result.

**Comment by JonathanMagnan** [comment]
Hello @cuiliang ,

Thank you for reporting, we will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @cuiliang ,

Unfortunately, we still have not succeeded to fix this issue correctly without getting some side impact as we know some people use that feature in their code (Dict key is replaced by value).

However, we choose to add an option to disable this behavior as we understand not everyone wants it and as you show, it cause also some impact.

You can disable it with the options `DisableAutoReplaceDictionaryKey  = true`.

We will not close this issue as we might want to try it again but for now, using that new option will be the solution for this behavior.

**Comment by cuiliang** [comment]
Thank you! Got it~

Jonathan Magnan ***@***.***> 于2021年10月28日周四 上午12:21写道：
