### ISSUE TITLE
The Enumerable.Intersect seems doesn't work for IEnumberable<char>

### ISSUE THREAD

**Issue by ceastld** [zzzprojects/Z.Expressions.Eval#117]
The following statement will report an error.

```C#
using Z.Expressions;

namespace ConsoleApp1
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var context = new EvalContext();
            context.Execute(@"'aaa'.Intersect('a');");
        }
    }
}
```
The error is as follows

![image](https://user-images.githubusercontent.com/61349137/141302637-ebe48700-b232-43d2-89dd-a25ec39c7669.png)

```
Z.Expressions.Compiler.Shared.EvalException:“Oops! No applicable member has been found for the expression. The error occurred for expression "." at position 5 near ".Intersect('a');".”
```

but the `Intersect` method works for `List<string>`

**Comment by JonathanMagnan** [comment]
Hello @dyliu02 ,

Thank you for reporting, we can successfully reproduce it with your code and we will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @dyliu02 ,

The v4.0.63 has been released.

Could you test it and let us know if methods now work correctly with `IEnumerable<char>` interface like in this case?

Best Regards,

Jon

**Comment by ceastld** [comment]
Ok, I tested it, and it works correctly now.

Thank you @JonathanMagnan
