### ISSUE TITLE
string.Left method

### ISSUE THREAD

**Issue by lynnmiller** [zzzprojects/Z.Expressions.Eval#12]
I downloaded Eval-Expression.NET and am trying it out.

The following command works and returns "Lynn":

string result4 = Eval.Execute<string>("String.Copy(\"Lynn\")");

This command errors out.  

string result5 = Eval.Execute<string>("String.Copy(\"Lynn\").Left(1)");

Should I be able to do something like I am trying to do?  I am trying to understand the capabilities of this library by trying different scenarios.

Thanks.

**Comment by JonathanMagnan** [comment]
Hello @lynnmiller ,

The following statement `String.Copy("Lynn").Left(1);` is not a valid C# statement. It doesn't compile even without our library.

The short answer is no, you should not be able (unless we add this syntax in our library like we did with a few syntax).

If it's an extension method that you added to your library, you must register it. By example:

```csharp
RegisterExtensionMethod(typeof(Enumerable));
```

Let me know if that answer to your question.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @lynnmiller ,

We will close this issue since no more question has been asked.

Feel free to reopen if you need more information.

Best Regards,

Jonathan
