### ISSUE TITLE
Is there any chance to support newer c# version syntax?

### ISSUE THREAD

**Issue by cuiliang** [zzzprojects/Z.Expressions.Eval#127]
Thank you!

**Comment by JonathanMagnan** [comment]
Hello @cuiliang ,

I don't think at this moment we will make any change to support new syntax as we currently mainly focus to improve another library (EF Extensions) until at least the end of summer. From time to time, we add some new syntax but there is currently no short term plan at this moment to go on everything which new C# syntax has been recently added to try to support it.

Best Regards,

Jon

**Comment by cuiliang** [comment]
Thank you, got it~
