### ISSUE TITLE
Could not regard string as IEnumerable<char>

### ISSUE THREAD

**Issue by ceastld** [zzzprojects/Z.Expressions.Eval#128]
The expression below will get an error
```C#
new[]{"abc","def"}.SelectMany(x => x);
```
Error:
```C#
Oops! No applicable member has been found for the expression. The error occurred for expression "." at position 18 near ".SelectMany(x => x);".
```

And this is Ok
```C#
new[]{"abc","def"}.SelectMany(x => x as IEnumerable<char>);
```

```C#
Z.Expressions.Eval, Version=4.0.79.0
```

**Comment by JonathanMagnan** [comment]
Hello @ceastld ,

Thank you for reporting.

I will ask my developer to look if we can support this kind of scenario.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @ceastld ,

The v4.0.82 has been released.

Could you confirm for us that everything works fine with the latest version?

Best Regards,

Jon

**Comment by ceastld** [comment]
Hi @JonathanMagnan
Thanks for fix this issue.
And I test it, everything works fine

**Comment by JonathanMagnan** [comment]
Hello again! 

Great to hear everything is working as expected. 

Don't hesitate to contact us if you need more information. 

Best regards, 

Jon
