### ISSUE TITLE
Error null parameter

### ISSUE THREAD

**Issue by vzsoft** [zzzprojects/Z.Expressions.Eval#134]
hi
i got error send null parameter in query 
`object query = context.Execute(@"var ss=""""; return ss=={0} ? 1: 2;", new object[] { null });`

Error : System.NullReferenceException: 'Object reference not set to an instance of an object.'

Version: 4.0.83

**Comment by JonathanMagnan** [comment]
Hello @vzsoft ,

Thank you for reporting, my developer is currently looking to fix this issue.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @vzsoft ,

The v4.0.84 has been released.

Could you look at it and confirm that my developer fixed this issue correctly?

Best Regards,

Jon

**Comment by vzsoft** [comment]
Nice Work

thank you
