### ISSUE TITLE
Broken NuGet package

### ISSUE THREAD

**Issue by TOuhrouche** [zzzprojects/Z.Expressions.Eval#135]
Hi,
All our builds are failing with the following error message 
`error NU5037: The package is missing the required nuspec file. Path: C:\a\1\.nuget\packages\z.expressions.eval\4.0.43`  
Anyone facing similar issues?

**Comment by JonathanMagnan** [comment]
Hello @TOuhrouche ,

That's a very old package, so nothing has changed on our side.

If this was the package you were already using in your previous build, there is a good chance that the issue come from your side and not our (the package is still the same and still available on NuGet).

Best Regards,

Jon

**Comment by TOuhrouche** [comment]
Thanks Jon. I upgraded to the latest NuGet package and the issue went away.
