### ISSUE TITLE
Can I not throw an exception when expression evaluation fails?

### ISSUE THREAD

**Issue by saber-wang** [zzzprojects/Z.Expressions.Eval#137]
for example：
```
Eval.Execute<bool?>("test==\"124\"", new {})
```
The following exception will be thrown:
```
Unhandled exception. Z.Expressions.Compiler.Shared.EvalException: Oops! The current expression is null. The error occurred for expression "test" at position 0 near "test==\"124\"".
   at  . (ExpressionScope , SyntaxNode , Func`3 )
   at  . (ExpressionScope , SyntaxNode , Expression , Boolean )
   at  . (ExpressionScope , SyntaxNode , Expression , Boolean )
   at  . (ExpressionScope , SyntaxNode , Expression , Boolean )
   at  . [ ](EvalContext , String , IDictionary`2 , Type , EvalCompilerParameterKind , ExpressionScope , String , Boolean , Boolean)
   at  . [ ](EvalContext , String , IDictionary`2 , Type , EvalCompilerParameterKind , Boolean , Boolean , Boolean )
   at Z.Expressions.EvalContext.Execute[TResult](String code, Object[] parameters)
```

I want to return `default`.

**Comment by JonathanMagnan** [comment]
Hello @saber-wang ,

Thank you for asking,

I can understand the reason when using a nullable type such as `bool?`.

Are you looking for a solution only for when the compilation fails (like this case) or also when the execution fails?

Best Regards,

Jon

**Comment by saber-wang** [comment]
@JonathanMagnan  Thank you for your answer. After reading your answer, I realized that the compilation phase failed.
Can I handle it at this stage?

**Comment by JonathanMagnan** [comment]
Hello @saber-wang ,

It depends on what you mean by "Can I handle it". What exactly do you want to do?

You can sure handle it with a try/catch but I'm not really sure what you are looking for.

When the compilation fail, the error causing it is raised, and the 2 followings properties are populated:
- OriginalCode: Your current expression
- ParsedCode: The expression we parsed as sometimes we do slight modification such as when using through LINQ

**Comment by saber-wang** [comment]
@JonathanMagnan  I don't want to throw an exception here because the object is dynamic.😁

**Comment by JonathanMagnan** [comment]
Hello @saber-wang ,

Your current example is an anonymous type, not an expando / dynamic object.

Expando and dynamic object will normally compile without problem but will indeed raise an error when executing if, for example the property in the expression doesn't exists.

**Comment by saber-wang** [comment]
@JonathanMagnan  That's right. I was negligent. Thanks for your help.
