### ISSUE TITLE
Web page is not rendering correctly

### ISSUE THREAD

**Issue by arsman-ahmad** [zzzprojects/Z.Expressions.Eval#140]
Hi,

I was looking for a `custom comparer` in `Dynamic Linq` while using `OrderBy`. I find that there's some issue on the page due to which the content is not loading correctly. The page having 04 content section and only first section is loading correctly. (I'm attaching `link` and `image` of the page here as well.)

**Link**
https://eval-expression.net/linq-dynamic-orderby-examples

**Image**

![Screenshot 2022-11-16 191132](https://user-images.githubusercontent.com/36694359/202203115-7536c95c-c543-42fd-9f38-c9569106c2b8.jpg)

**Comment by JonathanMagnan** [comment]
Hello @arsman051 ,

Thank you for reporting.

Indeed something is missing here. Look to happen on multiple pages.

We will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @arsman051 ,

A new version is now in production. We reviewed all pages in this section and has been fixed:

- The contents sections (See the `{% highlight text %}`
- The middle menu when not matching text
- The middle menu anchor link

Let me know if you see something else we missed
