### ISSUE TITLE
version 6.2.0: No applicable member has been found 

### ISSUE THREAD

**Issue by cuiliang** [zzzprojects/Z.Expressions.Eval#162]
This code will have problem:

```
var last = JArray.Parse("[]");
  last.Add("aaa");
```
Error: `Oops! No applicable member has been found for the expression. The error occurred for expression "." at position 38 near ".Add(\"aaa\");".`

Replace `var` with type name works.

```
JArray last = JArray.Parse("[]");
  last.Add("aaa");
```

**Comment by JonathanMagnan** [comment]
Hello @cuiliang ,

Thank you for reporting; we successfully reproduced the issue.

We will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @cuiliang ,

Just to let you know that a fix has been merged and will be released on November 12.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @cuiliang ,

The v6.2.2 is now available: https://github.com/zzzprojects/Eval-Expression.NET/releases/tag/v6.2.2

We have improved our better member resolution logic that was causing this error.

Let me know if everything works as expected.

Best Regards,

Jon

**Comment by cuiliang** [comment]
@JonathanMagnan Thank you~
