### ISSUE TITLE
Bug:NameSpace

### ISSUE THREAD

**Issue by vzsoft** [zzzprojects/Z.Expressions.Eval#2]
hi

[sample download](https://drive.google.com/open?id=0B9DILM3WqR1Obmd5QXFDZUFSNk0)

**Comment by zzzprojects** [comment]
Thank you vzsoft,

We will look at this issue this week and try to fix all issues which may be related to a namespace.

**Comment by zzzprojects** [comment]
Hello vzsoft,

The version 1.0.21 has been  released. We have fixed this issue and a few more which could happen with a similar scenario.

Can you confirm this issue is fixed?

Best Regards,

Jonathan

**Comment by vzsoft** [comment]
Hello Jonathan

the problem was solved

thank you so much

**Comment by vzsoft** [comment]
hi

sample error again in Z.Expressions.Eval.1.0.35 version

**Comment by zzzprojects** [comment]
Thank you, I will look at this in a few hours.

I will add some unit tests to make sure that will never happen again.

Best Regards,

Jonathan

**Comment by zzzprojects** [comment]
The bug has been fixed but not released yet.

We are currently looking if we should redo or not the "NewKeyword" code.

I will let you know more very soon.

Best Regards,

Jonathan

**Comment by zzzprojects** [comment]
Hello @vzsoft ,

The v1.0.36 has been released with the correction of this issue.

Be careful, in a few hours, we will also release the version 2.x support dot net core. However, the library will not be any more free (50 characters or less). So make sure you use the version 1.x

Best Regards,

Jonathan

**Comment by vzsoft** [comment]
Thank You
