### ISSUE TITLE
No applicable member has been found for the expression in Enumerable

### ISSUE THREAD

**Issue by rogerfar** [zzzprojects/Z.Expressions.Eval#20]
When I execute this code:

        static void Main(string[] args)
        {
            var eval = new EvalContext();
            eval.RegisterDomainAssemblies();

            const string test = @"var list = new List<Int32>();
    list.Add(2);
    list.Add(1);
    list = Enumerable.OrderBy(list, m => m).ToList();
    return list;
    ";
            var testList = Test();
            var invoiceAdd = eval.Execute<List<String>>(test);
        }

        private static IList<Int32> Test()
        {
            var list = new List<Int32>();
            list.Add(2);
            list.Add(1);
            list = Enumerable.OrderBy(list, m => m).ToList();
            return list;
        }

I get the following errors:
'Oops! No applicable member has been found for the expression.'

**Comment by JonathanMagnan** [comment]
Hello @yesman85 ,

Thank you for reporting,

We already found the cause of the issue, we will fix it and provide you a solution for next Monday.

Meanwhile, calling the method like this will work:

```csharp
const string test = @"var list = new List<Int32>();
list.Add(2);
list.Add(1);
list = list.OrderBy(m => m).ToList();
return list;
";
```

**Comment by rogerfar** [comment]
I tried that, unfortunately OrderBy is not whitelisted and it being pulled from the wrong library in my case.

**Comment by JonathanMagnan** [comment]
Hello @yesman85 ,

The v2.4.6 has been released.

I believe all issue related to this one or you provided by email has been solved in this version.

You do not longer need to try to `blacklist` some type.

Let me know if everything works fine.

Best Regards,

Jonathan

**Comment by rogerfar** [comment]
Yes this seems to work!
