### ISSUE TITLE
Update Wiki

### ISSUE THREAD

**Issue by nawfalhasan** [zzzprojects/Z.Expressions.Eval#22]
Update page https://github.com/zzzprojects/Eval-Expression.NET/wiki/vs-LINQ-Dynamic-Query-Library to include latest syntax.

These are wrong: 

    OrderByDynamic("x => x.P1")
    SelectDynamic("x => new {Y = x.P1, x.P2}")
    Where("x => x.P1 == 1 && x.P2 == 2")

Should be

    OrderByDynamic(x => "x.P1")
    SelectDynamic(x => "new {Y = x.P1, x.P2}")
    Where(x => "x.P1 == 1 && x.P2 == 2")

**Comment by JonathanMagnan** [comment]
Hello @nawfalhasan ,

Thank you for reporting.

The examples has been fixed.

Best Regards,

Jonathna
