### ISSUE TITLE
Unicode chars are not handled in member names

### ISSUE THREAD

**Issue by rodro75** [zzzprojects/Z.Expressions.Eval#27]
Hello guys,

I've found that the library thows an exception when it encounters member names containing accented letters, like in the following unit test.

<pre>
[TestMethod]
public void CanHandleUnicodeMemberNames()
{
    var context = new EvalContext { UseCache = false };
    var code = @"Quantità == 10";
    var dataContext = new {Quantità = 10};
    var result = context.Execute<bool>(code, dataContext);
    Assert.IsTrue(result);
}
</pre>

Given that c# allows for unicode characters in member names I didn't expect this behavior.

Thanks!

**Comment by JonathanMagnan** [comment]
Hello @rodro75 ,

Thank you for reporting. You are right, our library doesn't support accent.

We will look at the code this week and evaluate the complexity of implementing that this week.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @rodro75 ,

The v2.4.15 has been released.

Accent should now be supported for a variable name.

Let me know if that works correctly.

Best Regards,

Jonathan

**Comment by rodro75** [comment]
Hey @JonathanMagnan ,

I confirm that the issue is gone 👍 

Thank you very much for the rapid fix, you saved the day!

Bye,

-Rodro-
