### ISSUE TITLE
"Not" operator parsing problem

### ISSUE THREAD

**Issue by rodro75** [zzzprojects/Z.Expressions.Eval#29]
Hi guys,

This isn't a big concern, since there are workarounds, but I thought you might be interested.
Given an eval context where I registered this static method:

<pre><code>
    public static class MyMethods
    {
        public static bool GiveMeTrue()
        {
            return true;
        }
    }
</code></pre>

<pre><code>
            var context = new EvalContext {UseCache = false};
            context.RegisterStaticMember(typeof(MyMethods));
            context.RegisterType(typeof(MyMethods));
</code></pre>

The following works as expected:
<code>
            var result = context.Execute<bool>("GiveMeTrue()");
            Assert.IsTrue(result);
</code>

But the following throws a compile error: Oops! The type could not be found.
<code>
            var result = context.Execute<bool>("!GiveMeTrue()");
            Assert.IsFalse(result);
</code>

Unless I enclose the method invocation in parens:
<code>
            var result = context.Execute<bool>("!(GiveMeTrue())");
            Assert.IsFalse(result);
</code>

Now, if I write this the error message is differnet, actually more to the point I think:
-Missing left expression for binary keyword or operator "==" at position 14 near "== true"-
<code>
            var result = context.Execute<bool>("!GiveMeTrue() == true");
            Assert.IsFalse(result);
</code>

Again, by using extra parens the parser get it right.
<code>
            var result = context.Execute<bool>("!(GiveMeTrue()) == true");
            Assert.IsFalse(result);
</code>

-Rodrigo-

**Comment by JonathanMagnan** [comment]
Hello @rodro75 ,

Thank you for reporting,

We will for sure look at it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @rodro75 ,

The v2.4.18 has been released.

The `NOT` operator should now work correctly with all your cases.

Best Regards,

Jonathan

**Comment by rodro75** [comment]
Hi @JonathanMagnan ,

I confirm that it now works as expected.

Thank you very much.

-Rodrigo-
