### ISSUE TITLE
Cannot add library to UWP

### ISSUE THREAD

**Issue by pschmerling** [zzzprojects/Z.Expressions.Eval#3]
I want to use the library in a application on Windows IoT on Raspberry PI. But when adding the library using nuget I get the following error:
`System.Reflection.Emit.ILGeneration 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm-aot).
System.Reflection.Emit.ILGeneration 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x64-aot).
System.Reflection.Emit.ILGeneration 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86-aot).
Package restore failed for 'ProjectName'.
Package restore failed. Rolling back package changes for 'ProjectName'.`

My project.json is this:
`{
  "dependencies": {
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2",
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}`

Do you think this issue can be solved on Z.Expressions.Eval?

**Comment by JonathanMagnan** [comment]
Hello @pschmerling ,

Thank you for reporting this issue.

We have found a lot of useful information about it here: https://github.com/StefH/System.Linq.Dynamic.Core/issues/33

The issue seems to be general to a lot of libraries. System.Reflection.Emit.ILGeneration is not supported yet in UWP project on aot runtimes (ahead of time).

We will investigate more this issue and let you know soon.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @pschmerling ,

We will close this request since we have not done anything since last year and I don't think we can do anything about it due to how the library is made.

Best Regards,

Jonathan
