### ISSUE TITLE
Not able to parse if(true)

### ISSUE THREAD

**Issue by ashokrayal** [zzzprojects/Z.Expressions.Eval#30]

**Comment by JonathanMagnan** [comment]
Hello @Ashokrayal ,

Could you provide an example? We have a few unit test with this expression which seems to work.

For example:

```csharp
var x = Eval.Execute("if(true) return 1; return 2;");
```

Best Regards,

Jonathan

**Comment by Ashokrayal** [comment]
It is failing at the time of scope compile.

`string expression = "if(true){}"
 var p = new CompiledExpression(expression) { TypeRegistry = new TypeRegistry() };
 return p.ScopeCompile<Scope>();`

object reference null reference is occurring at the last line.

**Comment by ashokrayal** [comment]
It is failing at the time of scope compile.

`string expression = "if(true){}";
var p = new CompiledExpression(expression) { TypeRegistry = new TypeRegistry() }; 
return p.ScopeCompile<Scope>();`

object reference null reference is occurring at the last line.

**Comment by JonathanMagnan** [comment]
Hello @Ashokrayal ,

You are currently using the `ExpressionEvaluator` library which has multiple issues and obsolete (no longer supported).

If that's possible, I recommand you to move to http://eval-expression.net/ (paid library). That's the library we support and which work with your expression.

Best Regards,

Jonathan
