### ISSUE TITLE
Question: "sys:bool"

### ISSUE THREAD

**Issue by Mike-E-angelo** [zzzprojects/Z.Expressions.Eval#4]
Hey there,

Pretty impressed with this library.  I am running into a problem, however.  It seems as if expressions such as `sys:bool` resolve to the `bool` type.  Which is pretty cool.  Unfortunately this conflicts with how I am using the same tokens. :)  For some context, I am using `Eval` as such:

```
public object Get(string parameter)
{
	try
	{
		var invoke = Eval.Compile(parameter).Invoke();
		return invoke;
	}
	catch (Exception)
	{
		return Eval.Compile(parameter.Quoted()).Invoke();
	}
}
```

If there is an error in parsing, then I wrap it as a string and try again.  So, I am expecting `sys:bool` to fail, at which point I would wrap it in quotes and try again (thereby returning a string).

Is there a way to turn off this magic, by chance?

**Comment by JonathanMagnan** [comment]
Hello @Mike-EEE ,

Thank you for reporting.

We are currently looking at this issue. We are currently unsure if we want to treat it as an error or not...

Some similar syntax could be valid (I must admit that's not very similar!):
```csharp
int i = 0;
sys:i++;
goto sys;
```

We will investigate this issue tomorrow or during this weekend. We will for sure come back with a solution (in the worse case, adding an option to disable goto statement).

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
There is something that bothers us,

Is there a reason when you are not checking with the Contains method if the "parameter" to evaluate has the character ':'?

**Comment by Mike-E-angelo** [comment]
Ah, that is correct, @JonathanMagnan!  I didn't even consider (or realize 👼) that as a valid statement.  I never use `goto` so. :)

In my case I am evaluating a single line, without a semicolon.  However I see now from my perspective that this is 100% not your issue, but is rather mine.  Your API is working as expected... maybe a little too well. 😄  I will figure something on my end.  Thank you for the prompt reply!
