### ISSUE TITLE
Dynamic update Query in EF core

### ISSUE THREAD

**Issue by kinshuk4u4u** [zzzprojects/Z.Expressions.Eval#48]
Hello 

My requirement is  i want to find  table  which have foreign key  of  Master table  then i want to update  foreign key all this table.

**Requirement with example** 

I have i product table. its primary key is  PkProductID  . its in have foreign key in multipal table. I want to find all the table which have foreign key on productid and update  prodductid  from  other productid inall the table .

Please conform this functionality have in your product ?

**Comment by JonathanMagnan** [comment]
Hello @kinshuk4u4u ,

Eval-Expression.NET is an expression evaluator. It can allow you to create dynamic query in `EF Core` but from what I understand, that's not at all what you want to achieve.

So no, I do not believe this product will help you unless a misunderstand your requirement.
