### ISSUE TITLE
The parser should give error messages at least as good as from the C# compiler.

### ISSUE THREAD

**Issue by daveyostcom** [zzzprojects/Z.Expressions.Eval#55]
This is really unusable:

> Run-time exception (line 116): Object reference not set to an instance of an object.
> 
> Stack Trace:
> 
> [System.NullReferenceException: Object reference not set to an instance of an object.]
> at .(ExpressionScope , SyntaxNode )
> at .(ExpressionScope , SyntaxNode , Expression , Boolean )
> at .(ExpressionScope , SyntaxNode , Expression , Boolean )
> at .(ExpressionScope , SyntaxNode , Expression , Boolean )
> at Z.Expressions.CodeCompiler.CSharp.ExpressionParser.ParseSyntax(ExpressionScope scope, SyntaxNode node, Type resultType)
> at .[](EvalContext , String , IDictionary`2 , Type , EvalCompilerParameterKind , Boolean , Boolean )
> at Z.Expressions.Eval.Compile(String code, IDictionary`2 parameterTypes)
> at Program.evalDemo5() :line 116
> at Program.testEval() :line 22
> at Program.Main() :line 11

**Comment by JonathanMagnan** [comment]
Hello @daveyostcom ,

Please provide the code that raises this error and we will improve it. We have improved a lot of error message in the past and we keep improving them as we get it.

Best Regards,

Jonathan

**Comment by daveyostcom** [comment]
Here's an error message from [this example](https://dotnetfiddle.net/ZE67wT):

Run-time exception (line 116): Object reference not set to an instance of an object.

Stack Trace:

[System.NullReferenceException: Object reference not set to an instance of an object.]
   at .(ExpressionScope , SyntaxNode )
   at .(ExpressionScope , SyntaxNode , Expression , Boolean )
   at .(ExpressionScope , SyntaxNode , Expression , Boolean )
   at .(ExpressionScope , SyntaxNode , Expression , Boolean )
   at Z.Expressions.CodeCompiler.CSharp.ExpressionParser.ParseSyntax(ExpressionScope scope, SyntaxNode node, Type resultType)
   at .[](EvalContext , String , IDictionary`2 , Type , EvalCompilerParameterKind , Boolean , Boolean )
   at Z.Expressions.Eval.Compile(String code, IDictionary`2 parameterTypes)
   at Program.evalDemo5() :line 116
   at Program.testEval() :line 22
   at Program.Main() :line 11

**Comment by JonathanMagnan** [comment]
Thank you,

I have assigned this task to one of my developers. We usually try to add a few more every time.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @daveyostcom ,

Unfortunately, it looks you updated your Fiddle to a working one.

So my developer is not able to investigate your error as there is currently no error in the provided Fiddle.

Could you create a new one that shows the error?

Best Regards,

Jonathan

**Comment by daveyostcom** [comment]
Here you go:
[parser error from private base class field](https://dotnetfiddle.net/lYGOif)

**Comment by JonathanMagnan** [comment]
Thank you ;)

**Comment by JonathanMagnan** [comment]
Hello @daveyostcom ,

A new version has been released.

Some error message such as this one has been improved:

> Run-time exception (line 114): valueBase is inaccessible due to its protection level. At position 71 near "valueBase;
      x1 + x2

Best Regards,

Jonathan

**Comment by daveyostcom** [comment]
Thanks
