### ISSUE TITLE
Can't seem to access a member of a base class

### ISSUE THREAD

**Issue by daveyostcom** [zzzprojects/Z.Expressions.Eval#56]
See `evalDemo5()` in [my example code](https://dotnetfiddle.net/ZE67wT).

**Comment by JonathanMagnan** [comment]
Hello @daveyostcom ,

I believe this one is an expected behavior.

Your member of base class is currently private. Which mean, you cannot access it from child.

You need to set it either public or protected

```csharp
class HolderBase {
	public int valueBase = 16;
}

// or

class HolderBase {
	protected int valueBase = 16;
}
```

Let me know if that's now working as expected.

Best Regards,

Jonathan

**Comment by daveyostcom** [comment]
Silly me!

Sorry for the bother.
