### ISSUE TITLE
need a better error message when a script tries to access a nonpublic symbol

### ISSUE THREAD

**Issue by daveyostcom** [zzzprojects/Z.Expressions.Eval#57]
Example [here](https://dotnetfiddle.net/BHSa67).

Btw, why must a symbol be public to be usable from a script within the same class?

**Comment by JonathanMagnan** [comment]
I would have expected that protected would have worked as well.

We will look at it

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @daveyostcom ,

Is there a reason why you want access to the protected property? They are not public, you cannot access them either outside of your class, so why do you expect to be able to access them via our library?

**Comment by daveyostcom** [comment]
Well that's actually one of my questions: what is the execution environment of the compiled code? I assumed that it somehow runs in the context of the `this` that's passed to it.

**Comment by JonathanMagnan** [comment]
The run is code as if it was an external library that executes it (well, that's, in fact, the case). By default, we cannot register non public method via `RegisterAssembly`, since WAY too many members will be registered.

But we could add an overload that registers it, that's very easy.

So let say the execution environment is outside of your library.

**Comment by daveyostcom** [comment]
I have updated the comment in my example to explain this, in case anyone looks.

**Comment by JonathanMagnan** [comment]
Great ;)

Can we close this issue?

**Comment by daveyostcom** [comment]
Hi,

If you want, I could vastly improve your documentation. Here is something I posted today. I can give you more writing samples.
https://stackoverflow.com/questions/55875809/graphviz-trouble-with-grid-layout-using-pos-attribute

I would start by asking you a bunch of questions to get to a deep understanding. Then present the information so everyone could get it immediately.

Best,

Dave
https://www.linkedin.com/in/dave-yost-b34870/

**Comment by JonathanMagnan** [comment]
Hello @daveyostcom ,

Sure, you can contact me directly here: info@zzzprojects.com

Getting some help with the documentation is always appreciated ;)

Best Regards,

Jonathan
