### ISSUE TITLE
eval error

### ISSUE THREAD

**Issue by daveyostcom** [zzzprojects/Z.Expressions.Eval#58]
I intended [this example](https://dotnetfiddle.net/udZfWL) to be equivalent to an example in [a previous report](https://github.com/zzzprojects/Eval-Expression.NET/issues/57), but it doesn't work, and I don't understand the error message:
```
Run-time exception (line 23): Oops! No applicable member has been found for the expression. The error occurred for expression "addInput" at position 7 near "addInput(2);
      addInp".
```

**Comment by JonathanMagnan** [comment]
There is no applicable member with the name "addInput",

A member is a property, method, constructors, fields, etc.

In this Fiddle, I don't find anything either with the name "addInput".

Let me know if that explains better the error message.

**Comment by daveyostcom** [comment]
I fiddled with the fiddle to add lines that were strangely missing.

**Comment by JonathanMagnan** [comment]
Oh now it makes sense ;) We will look at it.

**Comment by JonathanMagnan** [comment]
Hello @daveyostcom ,

It's possible to register static member but that doesn't work with non-static member. An instance must exist and it's impossible for our library which class instance it should use.

One way to make it possible is by providing the instance to the execute method

```csharp
var result = Eval.Execute(text, this);
```

**Comment by daveyostcom** [comment]
I'm fine with that. Thanks.  Is it faster to call Execute rather than Compile followed by calling the compiled code? If so, how much.

**Comment by daveyostcom** [comment]
I updated the test case, but now I wonder why it produces no output.

**Comment by JonathanMagnan** [comment]
> Is it faster to call Execute rather than Compile followed by calling the compiled code

Exactly the same performance. The `Execute` always call the compile and then execute the returned delegate.

The compile method will be faster when you need to execute the same method multiple time. For example in a loop. The execute method is still fast but needs to build a key and check in a cache if the compiled version exists and that makes it slower than directly using the compiled delegate.

**Comment by JonathanMagnan** [comment]
> I updated the test case, but now I wonder why it produces no output.

You don't have any Console.WriteLine but you might use a different fiddle. Work fine on my side

**Comment by daveyostcom** [comment]
Fixed. Thanks!

**Comment by JonathanMagnan** [comment]
Great :) 

Let me know if we can close this issue.
