### ISSUE TITLE
The Column name in the expression is limited to 13 characters other wise it returns an error 

### ISSUE THREAD

**Issue by waleedabuyahia** [zzzprojects/Z.Expressions.Eval#63]
"Oops! No applicable member has been found for the expression. The error occurred for expression \".\" at position 3 near \".Where(x => x.[ColName]\".",

if the expression is more than 13 characters it will return this error

**Comment by JonathanMagnan** [comment]
Hello @waleedabuyahia ,

Is it possible for you to provide a full example?

We have many expressions (include LINQ) that use more than 13 characters and they are all workings.  So I believe we are missing a piece of important information.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @waleedabuyahia,

Since our last conversation, we haven't heard from you. 

don't hesitate to send us an example!

Best regards, 

Jon

**Comment by JonathanMagnan** [comment]
Hello @waleedabuyahia 

A quick reminder that we are here to assist you!

Feel free to send us an example! 

best regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @waleedabuyahia 

Since we haven't heard back, we will close this issue. 

Feel free to contact us once you can provide more information. 

Best regards,

Jon
