### ISSUE TITLE
Letter "E" is always treated as Natural Log even if it is passed to Eval() as variable.  

### ISSUE THREAD

**Issue by hardikchheda13** [zzzprojects/Z.Expressions.Eval#65]
Maybe this is because E is literal in C#. Need a way to distinguish when it can be treated as natural log and when it needs to be treated as Variable.

**Comment by JonathanMagnan** [comment]
Hello @hardikchheda13 

Would it be possible to provide a description of your issue

**Comment by JonathanMagnan** [comment]
Which version are you using?

I remember now the issue and it's supposed to be fixed a few months ago.

Best Regards,

Jon

**Comment by hardikchheda13** [comment]
The nuget packege I am using is 2.9.45. Thanks.

**Comment by hardikchheda13** [comment]
I update the package and it works fine, thank for your help.

**Comment by JonathanMagnan** [comment]
Awesome! 

We are glad everything is working out for you!

Don't hesitate to contact us for questions or issues.

Best regards, 

Jon
