### ISSUE TITLE
Bug: generic list full name

### ISSUE THREAD

**Issue by vzsoft** [zzzprojects/Z.Expressions.Eval#7]
hi

use: error
System.Collections.Generic.List<System.Collections.Generic.List<System.String>
use: not error
System.Collections.Generic.List<List<System.String>>

sample:
```

            var context = new EvalContext();
            context.RegisterType(typeof(System.Collections.Generic.List<>));
            context.RegisterType(typeof(string));

            //Not Error
            var xx2 = context.Compile<Func<System.Collections.Generic.List<System.String>, object>>(@"
                var lst = new System.Collections.Generic.List<List<System.String>>();
                return lst;", "reader");

            //Error
            var xx = context.Compile<Func<System.Collections.Generic.List<System.String>, object>>(@"
                var lst = new System.Collections.Generic.List<System.Collections.Generic.List<System.String>>();
                return lst;", "reader");
```

**Comment by JonathanMagnan** [comment]
Hello @vzsoft ,

Thank you for reporting.

We have started to investigate the issue. We hope to complete tomorrow or later this week.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @vzsoft ,

The v2.1.1 has been released.

We have fixed issue with namespace when used in a generic type.

Let me know if that's now working.

Best Regards,

Jonathan

**Comment by vzsoft** [comment]
Thank you
