### ISSUE TITLE
Why a get error?

### ISSUE THREAD

**Issue by bqio** [zzzprojects/Z.Expressions.Eval#71]
![Screenshot_34](https://user-images.githubusercontent.com/45086516/76187290-63a3a080-61ee-11ea-9774-be05c374174d.png)

**Comment by JonathanMagnan** [comment]
Hello @bqio ,

Thank you for reporting,

We will look at this.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @bqio ,

The v3.1.7 has been released.

This issue should now be fixed.

Could you try it and let us know if everything works?

**Comment by Zeinabam** [comment]
hello @bqio,

Since our last conversation, we haven't heard from you.

Did you get the time to try the v3.1.7?

Don't hesitate to contact us for questions, issues or feedback. 

Best regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @bqio,

Since our last conversation, we haven't heard from you. 

Did you get the chance to try the v3.1.7?

Don't hesitate to contact us for questions, issues or feedback.

Best regards, 

Jon

**Comment by JonathanMagnan** [comment]
Hello @bqio 

A quick reminder that the v3.1.7 has been released.

feel free to contact for feedback regarding the latest version. 

Best regards, 

Jon
