### ISSUE TITLE
Error when parsing string interpolation expression with spaces

### ISSUE THREAD

**Issue by maxwave11** [zzzprojects/Z.Expressions.Eval#72]
Eval.Execute("$'{234234 }'") //space before closing curly brace

**Comment by JonathanMagnan** [comment]
Hello @maxwave11 ,

Thank you for reporting, we will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @maxwave11 ,

A new version has been released.

This issue is now be fixed.

Let me know if everything works as expected.
