### ISSUE TITLE
Formatting not works inside string interpolation expressions

### ISSUE THREAD

**Issue by maxwave11** [zzzprojects/Z.Expressions.Eval#73]
Eval.Execute("$'the date is { DateTime.Now:dd/MM/yyyy}.'")

**Comment by JonathanMagnan** [comment]
Hello @maxwave11 ,

Thank you for reporting, we will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @maxwave11 ,

A new version has been released.

This issue is now be fixed.

Let me know if everything works as expected.

**Comment by maxwave11** [comment]
It works, thank you!
