### ISSUE TITLE
Expression error using Empty Type

### ISSUE THREAD

**Issue by vzsoft** [zzzprojects/Z.Expressions.Eval#75]
Hi,

I got Error in Empty Type (**Test = new { }**)

my class:
```javascript
    public class AppUser 
    {
        public string Name { get; set; }
        public int? Age { get; set; }
    }
```

my code:
```javascript

var lst = Enumerable.Range(1, 10).Select(x => new AppUser() { Name = "1", Age = x }).ToList();

Eval.Execute("({0}).Select(x => new {x.Name, Test = new { } }).ToList()", lst);

```

Thank you

**Comment by JonathanMagnan** [comment]
Hello @vzsoft ,

Thank you for reporting. I didn't know it was possible to create an anonymous without any property (never think about it!).

We will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @vzsoft ,

The v4.0.0 has been released.

We now support empty anonymous.

Please make sure to check your expression when you upgrade since the v4.0.0 got a big logic re-write: https://github.com/zzzprojects/Eval-Expression.NET/releases/tag/v4.0.0

**Comment by vzsoft** [comment]
thank you so much

**Comment by JonathanMagnan** [comment]
Hello @vzsoft 

Did you get the time to try the latest version?

Looking forward to hearing from you,

Jon

**Comment by vzsoft** [comment]
Hello Jonathan

yes, i got version 4 and great work

**Comment by JonathanMagnan** [comment]
Awesome!

don't hesitate to contact us for questions, issues or feedback.

Best regards, 

Jon
