### ISSUE TITLE
Can not call member of Excel interop object

### ISSUE THREAD

**Issue by cuiliang** [zzzprojects/Z.Expressions.Eval#76]
I am using Microsoft.Office.Interop.Excel to work with excel.
When I pass a Workbook object to the expression, there will be NullReference exception.

![image](https://user-images.githubusercontent.com/1972649/85939323-e475dc00-b946-11ea-8a58-c19253d071ec.png)

**Comment by JonathanMagnan** [comment]
Hello @cuiliang ,

Do you think you could provide us a runnable example with this error?

It will make easier for my developer to get started.

Looking at this online example, it should be something that we could be able to support: https://dotnetfiddle.net/NBPqHU

Best Regards,

Jon

**Comment by cuiliang** [comment]
[TestExcelInterop.zip](https://github.com/zzzprojects/Eval-Expression.NET/files/4845645/TestExcelInterop.zip)

Please try this project.  You must have Microsoft excel running before run this sample.

thankyou.

**Comment by JonathanMagnan** [comment]
Hello @cuiliang ,

Thank you for the project.

The v4.0.2 has been released.

Could you try it and let us know if we now support `Marshal` object like the one you are using correctly?

Best Regards,

Jon

**Comment by cuiliang** [comment]
@JonathanMagnan It's working now. Thank you! Great job!
