### ISSUE TITLE
Difference between 4.0.2 to 4.0.3

### ISSUE THREAD

**Issue by se** [zzzprojects/Z.Expressions.Eval#79]
Hi, I have not much information but between 2 versions there is a huge performance difference. 

Do you guys know what could happen?

**Comment by JonathanMagnan** [comment]
Hello @se,

The v4.0.3 bring only a very tiny change:

```csharp
if (expression == null)
{
	throw new Exception(ExceptionMessage.FormatNear("Oops! A null expression has been found. A not null statement was expected.", argument));
}
```

That's all! So the new version should not cause any performance difference noticeable.

Besides the first use (JIT Compilation), everything looks to run very fast.

Do you have an example that we could try?

Best Regards,

Jon

**Comment by se** [comment]
My bad, upgraded from 3.0.14 to 4.0.3.

**Comment by JonathanMagnan** [comment]
Probably coming with the v4.0.0 that solve now in iterations some method previously solved in recursivity.

Do you still have an example that we could try and compare?

**Comment by se** [comment]
I think we can close this issue. There was a misunderstanding about the process. Sorry to bother.
