### ISSUE TITLE
something wrong with the dynamic

### ISSUE THREAD

**Issue by cesaryuan** [zzzprojects/Z.Expressions.Eval#87]
```
var context = new EvalContext();
context.Execute(@"
      dynamic jpart = new Dictionary<string, object>();
      jpart[""dw""] = 1;");
```
Execute above sentences in the VS. It throw the error like this. But it should work.

> System.InvalidCastException:“无法将类型为“System.Linq.Expressions.NewArrayInitExpression”的对象强制转换为类型“System.Linq.Expressions.ConstantExpression”。”

> System.InvalidCastException: "Cannot cast an object of type "System.Linq.Expressions.NewArrayInitExpression" to type "System.Linq.Expressions.ConstantExpression"."

**Comment by JonathanMagnan** [comment]
Hello @cesaryuan ,

Thank you for reporting, we will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @cesaryuan ,

The v4.0.26 has been released.

Let me know if your issue has been correctly solved.

Best Regards,

Jon

**Comment by cesaryuan** [comment]
> Let me know if your issue has been correctly solved.

Thank you! It works for me.
