### ISSUE TITLE
Bug: typeof namespace full name

### ISSUE THREAD

**Issue by vzsoft** [zzzprojects/Z.Expressions.Eval#9]
Hi

i got error this code:

```javascript
           var context = new EvalContext();
            context.RegisterType(typeof(System.Collections.Generic.Dictionary<, >));
            context.RegisterType(typeof(System.Collections.Generic.List<>));

            context.RegisterType(typeof(string));

            var test2 = context.Compile<Func<System.Collections.Generic.List<System.String>, object>>(@"
                var lst = typeof(System.Collections.Generic.List<System.Collections.Generic.List<System.String>>);
                return null;", "input");
```

**Comment by JonathanMagnan** [comment]
Hello @vzsoft ,

Thank you for reporting this issue. We successfully reproduced it and found out what's causing this issue.

We are currently investigating how to handle this case without impacting the code. More information will be very soon available.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @vzsoft ,

Sorry for the long waiting.

The v2.1.3 has been released:
https://github.com/zzzprojects/Eval-Expression.NET/releases/tag/v2.1.3

Best Regards,

Jonathan

**Comment by vzsoft** [comment]
Thank you
