### ISSUE TITLE
Is it possible to support nameof operator?

### ISSUE THREAD

**Issue by cesaryuan** [zzzprojects/Z.Expressions.Eval#98]
Is it possible to support [nameof](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/nameof) operator to get the variable name?
```csharp
Console.WriteLine(nameof(System.Collections.Generic));  // output: Generic
Console.WriteLine(nameof(List<int>));  // output: List
Console.WriteLine(nameof(List<int>.Count));  // output: Count
Console.WriteLine(nameof(List<int>.Add));  // output: Add

var numbers = new List<int> { 1, 2, 3 };
Console.WriteLine(nameof(numbers));  // output: numbers
Console.WriteLine(nameof(numbers.Count));  // output: Count
Console.WriteLine(nameof(numbers.Add));  // output: Add
```

**Comment by JonathanMagnan** [comment]
Hello @cesaryuan ,

We will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @cesaryuan ,

The v4.0.36 has been released.

Could you try it and let us know if everything is working as expected for the `nameof` operator?

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @cesaryuan ,

Since our last conversation, we haven't heard from you!

Did you get the chance to try the v4.0.36?

Don't hesitate to contact us for further assistance,

Jon

**Comment by cesaryuan** [comment]
I'm sorry to reply to you so late. I've tried and it performs well. Thank you.
